# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-03 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mutualfund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfund',
            old_name='name',
            new_name='fundname',
        ),
    ]
